### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by konradbeck-creditech** [berehovskyi/apex-stream#2]
We currently want to use this package in a namespace'd package but Salesforce doesn't allow this and will require us to repackage it with a namespace.

What are your thoughts are namespacing this package?

**Comment by berehovskyi** [comment]
Hi, 

Thank you for reaching out and considering Apex Stream Framework for inclusion in your project/package. The challenges you're facing are clear to me, but the idea of the framework is open-source, and namespace-free ensuring maximum flexibility and accessibility.

On the other hand, the open-source nature (MIT License) of Apex Stream Framework allows embedding the framework's sources (with the license) directly into your projects/packages without limitations. If you want to reuse it across multiple projects/packages you might consider creating your own separate lib packages (to include even more open-source libraries, e.g. query builder, trigger framework, etc.) with your namespace. You don't have to worry about security review because Apex Stream Framework does not contain any SOQL or DML invocations.

Best regards,
Oleh Berehovskyi
