### ISSUE TITLE
A non-null value as always greater than a null value

### ISSUE THREAD

**Issue by konradbeck-creditech** [berehovskyi/apex-stream#7]
SObjectPredicates.isGreater()

comparison of all primitive types and considers a non-null value as always greater than a null value.

Integer num1 = 10;
Integer num2 = null;

Assert.isFalse(num1 < num2);

This goes against the default behavior of Salesforce.

**Comment by berehovskyi** [comment]
Hi @konradbeck-creditech,

Thank you for bringing this up. You’re absolutely right about the behavior, but this is documented in apex-docs:

> Unlike the standard `>` "greater than" operator, the predicate function supports comparison of all primitive types and considers a non-null value as always greater than a null value.

This design choice is due to the underlying use of Comparers in predicates. One of the key properties of a Comparer, as defined by its [contract](https://docs.oracle.com/javase/7/docs/api/java/util/Comparator.html#compare(T,%20T)), is **anti-symmetry**:

> sgn(compare(x, y)) == -sgn(compare(y, x))

Without adhering to this constraint, sorting operations could yield incorrect results.

However, you can handle nullability using functional composition:

```apex
IPredicate isRevenueGt10AndNotNull = SObjectPredicates.isGreater('AnnualRevenue', 10)
    .andAlso(SObjectPredicates.isNotEqual('AnnualRevenue', (Object) null));

isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = null)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 0)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 10)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 15)); // true
```
Additionally, I wanted to share that I’m currently working on a package that enhances the API of our built-in functions, which will include support for predicates based on non-antisymmetric comparers.

Best regards.

**Comment by berehovskyi** [comment]
Hi @konradbeck-creditech,

I've added a non-antisymmetric Comparer in the latest release. This allows you to emulate the default behavior of Apex comparison operators. However, to achieve the desired behavior, you'll still need to use functional composition:
```apex
IPredicate isRevenueGt10AndNotNull = SObjectPredicates.isCompared(
    SObjectFunctions.get('AnnualRevenue'),
    Function.constant(10),
    Comparer.nonAntisymmetricOrder(),
    1
);
// Or
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = null)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 0)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 10)); // false
isRevenueGt10AndNotNull.test(new Account(AnnualRevenue = 15)); // true

IPredicate isRevenueLt10AndNotNull = SObjectPredicates.isCompared(
    SObjectFunctions.get('AnnualRevenue'),
    Function.constant(10),
    Comparer.nonAntisymmetricOrder(),
    -1
);

isRevenueLt10AndNotNull.test(new Account(AnnualRevenue = null)); // false
isRevenueLt10AndNotNull.test(new Account(AnnualRevenue = 0)); // true
isRevenueLt10AndNotNull.test(new Account(AnnualRevenue = 10)); // false
isRevenueLt10AndNotNull.test(new Account(AnnualRevenue = 15)); // false
```

It's not as concise as I would like, but I'm currently working on a package that will provide a fluent and flexible API for working with built-in functions.

Best regards.

**Comment by konradbeck-creditech** [comment]
Hi @berehovskyi ,

Awesome!

Will definitely check it out.
